### ISSUE TITLE
Create a buy me a beer/coffee feature

### ISSUE THREAD

**Issue by Ezielduhr** [jeroen1602/lighthouse_pm#106]
Love the app!
I was always strugeling with the light houses and noe I can easily manage them.

**Comment by jeroen1602** [comment]
I've applied for Github sponsors and paypal.me so I will add these buttons to the about page.
But I'm not sure what Google play (or even iOS if that ever happens) think of these options.

**Comment by jeroen1602** [comment]
I have done some research and Google does not allow you to add a sponsor button in your app unless it goes via their in app purchase system. This is probably the same for iOS. 

[Article about donate button](https://www.pcmag.com/news/google-pulls-open-source-android-app-for-having-donation-button)

But if you look at their own policy then Google play billing should not be used for "payments include peer-to-peer payments, online auctions, and tax exempt donations;" so they are very vague about it. [Link](https://support.google.com/googleplay/android-developer/answer/9858738).

I'll look into adding Google play in app payments for Google play releases and keeping the other ones for the web and F-droid releases.
