### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by zixinus** [jeroen1602/lighthouse_pm#24]
This is probably due to me using an old android, but: when I install the app (and give it permissions) I try to open it. Nothing happens. The app simply does not start. I sometimes see the screen flash either black or white and then return to the menu.
Phone: https://www.evolveo.com/en/strongphone-q7-lte with Android 5.1.1 
Version: 32bit ARM version, the 1.0.0 +2

Tried: 
- uninstalling and reinstalling. No change
-using arm64 solution but that won'T even install. 
- restarting the phone  and then opening the app. Get a flash of a white scren and then nothing.

**Comment by zixinus** [comment]
I just tried with my old tablet. Tablet: https://www.samsung.com/us/business/support/owners/product/galaxy-tab-a-7-0-wi-fi/
It also has Android 5.1.1

Here, the app outright crashes with arm32 version. Arm64 won't install.

**Comment by jeroen1602** [comment]
Thanks for the bug report. I think I found the problem.
The gradient that is used on the splash screen isn't supported on Android versions lower than 7.0 (24), thus the app crashing on boot.
I'm going to create a 1.0.1 release.

**Comment by jeroen1602** [comment]
The new release is live https://github.com/jeroen1602/lighthouse_pm/releases/tag/1.0.1%2B3
