### ISSUE TITLE
lighthouse won't move into group when assigned.

### ISSUE THREAD

**Issue by Virus-vr** [jeroen1602/lighthouse_pm#251]
I can create a new group, but I can't move my lighthouses into any group when assigning it and clicking save.

**Comment by madmini** [comment]
I had this issue as well, but a re-install seems to have fixed it for me. Maybe I did not have the most recent version installed.

**Comment by Virus-vr** [comment]
Thanks this fixed my issue.

> I had this issue as well, but a re-install seems to have fixed it for me. Maybe I did not have the most recent version installed.

I thought I already tried that, but apparently I didn't lol
