### ISSUE TITLE
Request - Blink lighthouse light option

### ISSUE THREAD

**Issue by waynekwal** [jeroen1602/lighthouse_pm#41]
A shortcut to physically identify the lighthouse would be great, especially when troubleshooting.

**Comment by jeroen1602** [comment]
This is a good idea, not sure yet where I would put the button to do that.

But do you know if you can do this from steam vr? Because if the lighthouses don't have this functionality then I can't implement it.

**Comment by waynekwal** [comment]
There is an "Identify" option in SteamVR, but I'm not sure when specifically it does when invoked.  As to where to put the button, it might make sense to set up a new page for the lighthouse itself, which could be a source for more information beyond the power button, such as more buttons (like this), or detailed information like logs when you get an ff error on a lighthouse.

As an alternative, if the lights aren't hard-coded to the status in the firmware, maybe make them change colors between standby and on (or possibly even fast transition between the two states, but that might be hard on the lighthouse motors).

I'm currently troubleshooting an issue where a newly purchased lighthouse won't update, which is where these ideas are coming from.

**Comment by jeroen1602** [comment]
I can't actually choose the color that the lighthouses shows on it's LED nor can I choose how long it takes for it to boot up. All I can do is give it commands that it then follows.

I have found how to identify the lighthouse so I'll be working on that. I'm thinking of adding it at the metadata screen when you hold the power button. (This is just for the working on version and not in any release yet).

For myself the UUID is: `00001523-1212-EFDE-1523-785FEABCD124`

Also if you are having trouble updating your lighthouses try connecting them via the usb port on the back temporary.

**Comment by waynekwal** [comment]
Good call on the USB update, I'll give that a shot as well.  

I haven't looked at anything you can access command-wise, on the lighthouses, so thanks for the clarification.  A metadata screen that also has "additional commands" would be a great catch-all for anything like the identification option you find you want to add.  :)

**Comment by waynekwal** [comment]
Unrelated to the request, but since you suggested how to update the lighthouse, it ended up being stupid-simple.  The lighthouse was too far away from my PC to get a BT connection it was willing to update over.  I plugged it in at my desk and it started updating before I even had the USB cable in.  Thought that was kinda funny.
