### ISSUE TITLE
Small dark theme fixes.

### ISSUE THREAD

**Issue by jeroen1602** [jeroen1602/lighthouse_pm#65]
Some things don't look nice yet because of hard coded colors.

- [x] The background color for the disabled extra actions buttons don't look right.
- [ ] The selected color is almost invisible for:
  - [ ] The main device page.
  - [ ] The nicknames page.
  - [ ] The Vive Base stations ids.
- [x] Use light Github logo instead of dark one in section About on settings page.

**Comment by mralext20** [comment]
This is probably a similar case to the "we couldn't find any baseststions" text, wherein the color is set where the text/ button is made, and not as part of the theme

**Comment by jeroen1602** [comment]
Jep, still needs to be fixed though. But I thought I'd work on #65 first since it's easier to debug this one after.

Or do you want to handle this one?

**Comment by mralext20** [comment]
i can give it a look.

**Comment by jeroen1602** [comment]
I've completed #58 with pr #67. So it should be a lot easier to change the theme than going into your system's settings.

**Comment by mralext20** [comment]
iwas already using the quick settings title for flicking between them before.
