### ISSUE TITLE
Update the Google Play version

### ISSUE THREAD

**Issue by BlakCake** [jeroen1602/lighthouse_pm#66]
It seems the Google Play version it severely behind all the recent changes, are there any plans to update it soon? I would prefer to not have to build it myself.

**Comment by BlakCake** [comment]
Or at least create a new release since the last one was almost a month ago

**Comment by jeroen1602** [comment]
Yes, I hope to do that at the end of the week after finishing up [this milestone](https://github.com/jeroen1602/lighthouse_pm/milestone/1). Just a few small bugs with the dark theme support.

**Comment by jeroen1602** [comment]
See #68 for more info
