### ISSUE TITLE
(Android) add shortcuts for quicker use

### ISSUE THREAD

**Issue by jeroen1602** [jeroen1602/lighthouse_pm#8]
Android has the ability to add [shortcuts](https://developer.android.com/guide/topics/ui/shortcuts/). This is quite useful to change the state of a lighthouse group described in #7.

Add shortcut support for even quicker state changes.
Look into adding a [quick setting tile](https://developer.android.com/reference/android/service/quicksettings/TileService).

**Comment by jeroen1602** [comment]
#7 should be implemented first.

**Comment by jrtberlin** [comment]
Android 11 introduced [`Quick Access Device Controls`](https://developer.android.com/guide/topics/ui/device-control) in a dedicated menu. 
The user can decide to add a specific [`Control`](https://developer.android.com/reference/android/service/controls/Control) that "[r]epresents a physical object". The control tile additionally shows the current state of the object. A tile can be either an individual lighthouse or a group (see #7)

![Device Control](https://developer.android.com/images/device-control/device-control.gif)

I think this would be a great addition for Android 11 users.

Btw thanks for the app!

**Comment by jeroen1602** [comment]
This is a great idea!

I'll probably open a different issue for this once I'll start working on it.
The big problem is that my phone hasn't received the update to Android 11 yet and the emulator can't access Bluetooth.
So I'm guess I'll have to fake it all the way!

**Comment by jrtberlin** [comment]
@jeroen1602 Sorry, I didn't open an additional issue as this issue already covers shortcuts and quick tiles. As someone who has worked on Android apps with BLE functionality, I share the pain with the Android Emulator. I've gotten myself a testing device for that purpose, so if you need someone to test something on 11 let me know.
