### ISSUE TITLE
General question about BLE (feel free to close this)

### ISSUE THREAD

**Issue by philhzss** [jeroen1602/lighthouse_pm#83]
Hi jeroen1602

Firstly of course thank you so much for this program, I've been struggling with the "sometimes working" power-options in SteamVR for the basestations, I tried lighthouse-manager and it also just worked sometimes, but your program works 100% of the time and it's amazing, so thank you.

I just had a general unrelated question and I wasn't sure how to contact you, so feel free to delete this issue/close it, but if ever you can help me:
I'm trying to control a Bluetooth low-energy RGB LED strip in a program I'm writing. I've managed to use gatttool on my Raspberry Pi to read all the "handles" and "UUID"s for my device, but I'm wondering, how on earth am I supposed to know which handle does what?? So more specifically for you, I'm wondering how did you figure out what "commands" to send to the base stations to turn them on/off, and to read their state??? Is it just trial and error, or there's a trick??

Thanks a lot once again and if this sort of question is not welcome feel free to delete!!
Phil

**Comment by jeroen1602** [comment]
Thanks for the question

I had the fortune that someone else had already done the difficult work of reversing the BLE protocol that the lighthouse uses. But if you want to reverse engineer the protocol that the RBG LED strip uses. You could start connecting to it using a general purpose BLE app on your phone and just going through the BLE characteristics and see which are readable, writable, read/ writable and just mess around with it.

A useful thing to keep in mind is, if you were the developer that developed the BLE protocol  how would you sent the data that you need is as few bytes as possible. There is probably a byte that encodes the effect (if it has any) and 3 bytes that encode the RGB data, maybe even the RGB data per led light on the led strip.

You can also look at the chips on your RGB led controller and see if there is a chip on there that has documentation on how the BLE protocol works.

I hope this helps you with your reversing efforts!

P.S. Don't be afraid to tinker around you can always restart the  led strip if you soft-lock it.

Regards,
Jeroen

**Comment by philhzss** [comment]
Hi Jeroen, Thanks a lot for taking the time to reply!

Great idea for the app, I didn't even know such apps existed. I was using "gatttool" on my Raspberry Pi via SSH to try to check the characteristics, which was working but was quite clunky.. I just download a BLE scanner on the Google Play store, found the strip straight away and it easily displayed all the various properties, I'll definitely use this as a starting point, thanks a lot for the idea!

I actually found a [Github repo](https://github.com/egold555/Govee-H6113-Reverse-Engineering) a few days back with info on the same brand RGB strip, but I wasn't quite able to figure out what does what. Now that I can easily list the characteristics with my phone though, it'll definitely be easier to mess around with stuff. I'm not really worried about bricking the strip because as you said it can easily be reset and even if things went completely wrong, it was really cheap haha. But I'm sure it'll be okay.

For now it seems I'm automatically disconnected after like 2 seconds if I connect to it, but according to that other repo maybe I need to send a packet every 2 secs to stay connected. I'll mess around and we'll see, I'm really a beginner so this might be a bit much but either way it'll be fun to try!

Now time to see if I can make a little script that checks my schedule on my calendar and turns on the lights before I need to leave for work 😃 

Thanks again for your detailed and quick reply! Used your app again tonight, I didn't even know you could rename the stations, even greater than I thought! Feel free to close this I don't want to clutter your repo with unrelated issues

Regards,.
Phil
