### ISSUE TITLE
Add app to F-Droid

### ISSUE THREAD

**Issue by dudeofawesome** [jeroen1602/lighthouse_pm#88]
It would be nice to have the app release on F-Droid if possible. 
[Here's a link to their FAQ about getting your app included in the repo](https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included).

**Comment by jeroen1602** [comment]
I will look into adding the required F-Droid metadata so I can ad it to the F-Droid store.

I though that having a flutter app may be a problem but it seems that other apps also use flutter.

**Comment by jeroen1602** [comment]
Well I created a merge request to their data repo. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8441

Now let's hope that they will accept it.

**Comment by jeroen1602** [comment]
Good news the merge request has been merged so the app will show up in the fdroid store!

I will add an F-droid button to the readme once it has been released.

**Comment by jeroen1602** [comment]
Well it has taken a while before the app became live, but you can now get it from the F-Droid store.

https://f-droid.org/packages/com.jeroen1602.lighthouse_pm/

**Comment by dudeofawesome** [comment]
Awesome! I've migrated over to that version now 😄
